plugins { id 'com.android.application' }
android {
    namespace 'com.calc.plus'
    compileSdk 34
    defaultConfig {
        applicationId "com.calc.plus"
        minSdk 23
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
